name: frezka
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^6.0.6
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.11
  flutter_custom_tabs: ^1.0.4
  flutter_html: ^3.0.0-beta.1
  share_plus: ^7.0.2
  speech_to_text: ^6.3.0

  # State Management
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.2

  # FIREBASE
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2

  # COUNTRY PICKER
  country_picker: ^2.0.20

  # SOCIAL LOGIN
  google_sign_in: ^6.1.4
  the_apple_sign_in: ^1.1.1

  # BARCODE
  syncfusion_flutter_barcodes: ^22.1.38

  # Image
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  lottie: ^2.6.0

  #MAP
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # PAYMENT GATEWAYS
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^9.4.0
  flutter_paypal_checkout: ^1.0.1
  flutter_paystack: ^1.0.7
  flutterwave_standard: ^1.0.8

  flutter_localizations:
    sdk: flutter

  uuid: any
dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs --enable-experiment=records

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
